### ISSUE TITLE
Data loader

### ISSUE THREAD

**Issue by BoucheDimitri** [pminder/NeuralNetworks#1]
Hello, 

J'ai continué à bosser sur le data loader à partir de ta structure (Paul). J'ai pas encore posté, mais j'en suis au point ou j'ai un code qui tourne pour charger le fichier et stocker son contenu. Je le précise pour pas que l'on soit plusieurs à faire le même truc. 
Du coups, je conserve la structure en 2D où j'aplatis ?

**Comment by pminder** [comment]
Super, merci beaucoup !
Je pense que le mieux serait d'aplatir les images. De toute façon, on n'aura sans doute pas le temps d'aller jusqu'au deep learning et on n'utilisera donc probablement pas d'information spatiale... On devrait donc se retrouver avec un vector de valarrays, chaque valarray représentant une image aplatie. Qu'en penses-tu (il me semble que ce n'est pas un trop mauvais choix mais je ne suis pas catégorique non plus:) ?

**Comment by BoucheDimitri** [comment]
Je serais plus pour stocker les images dans des vector de double. La structure des valarray est vraiment beaucoup moins flexible et offre pas beaucoup plus de possibilité non ?

**Comment by BoucheDimitri** [comment]
Sinon je me demandais si ce ne serait pas une bonne idée de passer les tableaux de données directement comme attribut de classe de la classe DataLoader (qui serait plus une classe Data dans ce cas). Dans la mesure où nous n'avons pas vocation à modifier directement la base de donnée une fois que celle-ci est chargée. Qu'en pensez vous ? 
Sinon je ne suis pas sûr de comprendre ce que doit faire la methode Dataloader.load(), quand tu dis charger les données, tu pensais les stocker où ?

**Comment by pminder** [comment]
- Pour les valarray, ils sont optimisés pour le calcul scientifique (et parallèle d'après certains forums). C'est pour cette raison que je m'étais dis que ça pouvait être une bonne idée de les utiliser. Mais si tu préfères les vectors, c'est d'accord ;)
- Pour les données, ça recoupe le problème de renvoyer des pointeurs ou pas des pointeurs d'une certaine manière. Effectivement, si on abandonne les pointeurs, c'est sans doute mieux d'en faire une classe Data et de l'utiliser à chaque fois que l'on veut accéder aux données. C'est même sans doute plus dans l'esprit du C++ (je suis désolé mais j'ai tendance à toujours penser un petit peu en C...). Au niveau performances, il faudra juste essayer de ne pas oublier d'utiliser des références pour ne pas copier les images sans arrêt sur le stack...
- Du coup, Dataloader.load() peut simplement remplir les six attributs de la classe Dataloader (à renommer en Data?)

**Comment by BoucheDimitri** [comment]
Ok ok, je suis parti là dessus, j'essaie de poster ce soir le résultat :)

**Comment by pminder** [comment]
Bien, je pense que l'on peut adopter la nouvelle classe DataMNIST de Dimitri et supprimer tout ce qui avait attrait à DatLoader ?

**Comment by BoucheDimitri** [comment]
Yes, on peut effectivement supprimer dataLoader ;)

**Comment by pminder** [comment]
Je crois que l'on peut dire que c'est fait :)
