### ISSUE TITLE
Gsl library

### ISSUE THREAD

**Issue by BoucheDimitri** [pminder/NeuralNetworks#3]
C'est une galère pas possible d'utiliser Gsl sous windows (ne compile pas la moitié du temps pour des raisons inconnues) , pourrait-on utiliser une autre librairie pour les matrices ?

**Comment by BoucheDimitri** [comment]
Je propose Eigen qui est plus cross platform il me semble

**Comment by pminder** [comment]
Ah, d'accord, c'est un peu ce que je craignais avec la gsl. Je ne connais
pas eigeb mais je veux bien essayer. Ça me fait penser, est-ce qu'il ne
vaudrait pas mieux que la classe pour charger les données renvoie un vector
au sens de cplusplus de vecteurs au sens mathématique plutôt qu'un vector
de vectors à chaque fois au sens de cplusplus ?

**Comment by BoucheDimitri** [comment]
Oui tu as raison, si on utilise effectivement eigen, c'est effectivement indispensable que la classe pour la base de donnée nous renvoie un vector (au sens Cpp) de vector ( array au sens de eigen ). Dans ce cas pas besoin de passer par des valarray non ? Regarde si tu n'as pas de problèmes avec Eigen sous linux et une fois que tu me confirme, je change la classe DataMnist en conséquence et je peux changer ton code avec gsl en code avec eigen. Tiens moi au courant :)

**Comment by pminder** [comment]
Je viens d'installer eigen3 sur mon ordinateur. Ça marche sans aucun problème sur Linux ! Je suis donc OK pour que l'on commence à faire les changements. Si tu le fais avant moi, tant mieux :) Sinon, j'essaierai de le faire dans la soirée ou demain !

**Comment by BoucheDimitri** [comment]
Ok ok ! Parfait :) Je vais commencer à faire les changements sur datamnist en début d'aprem

**Comment by BoucheDimitri** [comment]
Je me charge de modifier la classe DataMnist pour qu'elle sorte des Eigen matrix. Je n'ai pas fini, mais c'est en cours donc ne commencez pas à le faire, ce serait inutile. Pour le reste je ne touche à rien donc feel free ;)

**Comment by BoucheDimitri** [comment]
En revanche je vais changer pas mal de truc dans la classe DataMnist, donc ne commencez pas à faire le lien entre votre travail et la classe DataMnist avant que je n'ai posté l'update (demain soir sans faute)

**Comment by pminder** [comment]
Ok, super, ça marche ! De mon côté, je vais voir ce que je peux faire sur
Network, qui soit indépendant du reste et demain on intègre les changements
et on fait le lien entre les deux.
