### ISSUE TITLE
Latex ?

### ISSUE THREAD

**Issue by BoucheDimitri** [pminder/NeuralNetworks#4]
Avez vous compris s'il faut faire un document explicatif en Latex pour le projet ?

**Comment by pminder** [comment]
Je n'ai pas vu explicitement qu'il fallait faire un document en Latex. Par
contre, Lucas m'a dit que le prof avait dit qu'il attendait un rapport très
court. Je ne sais donc pas dans quelle mesure on pourra parler des réseaux
de neurones dans le détail. Lucas m'a aussi dit qu'il rédigeait peut être
une partie du rapport ce weekend. Donc, je ne sais pas si tu as le projet
de le commencer aussi, mais mets toi bien d'accord avec lui au préalable :)
