### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by pminder** [pminder/NeuralNetworks#5]
Il me semble que nous en sommes au stade où notre code est fonctionnel mais trop lent pour tourner sur un petit ordinateur. Après y avoir assez longuement réfléchi ce weekend, j'ai comme l'impression que cela est dû à notre utilisation de la bibliothèque Eigen... Je sais, c'est très bizarre mais j'ai lancé un petit programme de multiplication de matrice très simple et Eigen va 20 fois moins vite que ce que j'ai codé en 10 minutes à la main... J'ai donc des doutes! Sans compter que le code python du site dont je vous ai parlé au début est plus rapide que notre implémentation C++... Plusieurs solutions s'offrent à nous:
- on considère que l'on a déjà bien travaillé sur ce projet, on fait tourner le code longtemps sur un PC puissant pour avoir un taux d'erreur convenable et on dit dans le rapport que l'on a rencontré (et analysé?) des problèmes de performances
- on estime que ça vaut le coup d'essayer de faire fonctionner le programme plus vite et on l'adapte pour qu'il fonctionne avec des types de données plus simples, en espérant qu'il soit nettement plus rapide à l'issue de cette adaptation... Ça ne représente pas un travail colossal mais il faut quand même compter une après midi je pense
  Qu'en pensez-vous ?

**Comment by BoucheDimitri** [comment]
Personnellement plus chaud pour la première solution. Le sujet est certes intéressant en soi, mais bon il y a tellement de trucs à faire pour l'ENSAE que j'aurais tendance à considérer que l'on y a mis assez de bonne volonté. Vous en pensez quoi ?
